<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Карточка товара");
if (!isset($_REQUEST["ELEMENT_CODE"]))
	LocalRedirect('/404.php');
?>

<?$APPLICATION->IncludeComponent("bitrix:breadcrumb", ".default", Array(
	"START_FROM" => "0",
		"PATH" => "",
		"SITE_ID" => "-",
	),
	false
);?>

<?$APPLICATION->IncludeComponent(
	"dev:catalog.element", 
	".default", 
	array(
		"IBLOCK_TYPE" => "catalogs",
		"IBLOCK_ID" => "1",
		"ELEMENT_ID" => "",
		"ELEMENT_CODE" => $_REQUEST["ELEMENT_CODE"],
		"SECTION_ID" => "",
		"SECTION_CODE" => $_REQUEST["SECTION_CODE"],
		"HIDE_NOT_AVAILABLE" => "N",
		"PROPERTY_CODE" => array(
			0 => "CAR_SEAT",
			1 => "VOICE_ACTIVATION",
			2 => "WEIGHT",
			3 => "CAMCORDER",
			4 => "TAB_MATTRESS",
			5 => "OUTSIDE_SIZE",
			6 => "INSIDE_SIZE",
			7 => "BOOSTER",
			8 => "IN_SOFA",
			9 => "AGE",
			10 => "OUTPUT_CHILD",
			11 => "DIMENSIONS",
			12 => "GABARITS_RAZLOJENNY",
			13 => "SIZE_COMPLECT",
			14 => "SIZE_STROLLER_SEAT",
			15 => "FRAME_UNSET",
			16 => "FRAME_SET",
			17 => "GABARITS_SLOJENNY",
			18 => "WARRANTY",
			19 => "GROUP",
			20 => "TWO_WAY",
			21 => "DISPLAY",
			22 => "WEIGHT_CHILD",
			23 => "DOP_FUNCTIONS",
			24 => "WEIGTH_LOAD",
			25 => "BOARD_CHANGING",
			26 => "STIFFNESS",
			27 => "WINTER_SUMMER",
			28 => "GAUGE",
			29 => "WHEELS",
			30 => "OPTIONS_WHEELS",
			31 => "COUNTSOTDEL",
			32 => "COUNT_POS",
			33 => "COUNT_REGIMENT",
			34 => "NUM_PROGRAMS",
			35 => "QUANTITY_PACKAGE",
			36 => "CNT_BOXES",
			37 => "FOR_ROOM",
			38 => "LOCKER",
			39 => "FEATURES_LOCKER",
			40 => "OPTIONS",
			41 => "BASKET4BUY",
			42 => "FIXING",
			43 => "COT",
			44 => "FEATURES_COT",
			45 => "CRADLE",
			46 => "MATERIAL_PRODUCTION",
			47 => "MATERIAL_WHEELS",
			48 => "MAT_BASKET4BUY",
			49 => "PLATING_STROLLERS",
			50 => "MEHANIZM_VRACH",
			51 => "TILTING_MECHANIZM",
			52 => "MECHANIZM_FRAME",
			53 => "MUSIC_MODULE",
			54 => "BACKREST_TILT",
			55 => "THE_CAPS",
			56 => "NIGHT_LIGHT",
			57 => "VOLUME",
			58 => "BASIS",
			59 => "FEATURES",
			60 => "REGIMENT",
			61 => "FRONT_WALL",
			62 => "SUITABLE_FOR",
			63 => "TIP_OFF",
			64 => "BEDSIDE_TABLE",
			65 => "MAKER",
			66 => "WORK_FROM",
			67 => "OP_FREQUENCY",
			68 => "ACTION_RADIUS",
			69 => "SIZE",
			70 => "SIZE_BED",
			71 => "SIZE_SLEEP",
			72 => "SIZE_CRADLE",
			73 => "LOCATION_CRADLES",
			74 => "ADJUST_SEAT",
			75 => "HEADREST",
			76 => "SEATBELTS",
			77 => "SEATBELTS2",
			78 => "SEAT_BELTS_SEAT",
			79 => "PARENT_HANDLE",
			80 => "CARRYING_HANDLE",
			81 => "HANDLE_BEFORE",
			82 => "CERT",
			83 => "SILICONE_PAD",
			84 => "COLIC",
			85 => "SUN_VIZOR",
			86 => "SOSTAV",
			87 => "RACK",
			88 => "TABLE",
			89 => "FEATURES_TABLE",
			90 => "TABLE_CHAIRS",
			91 => "FEATURES_CHAIRS",
			92 => "MATTRESS",
			93 => "TIMER",
			94 => "TYPE_ARENA",
			95 => "239",
			96 => "TYPE_BOX",
			97 => "TRANSFORMERS",
			98 => "BACK_ANGLE",
			99 => "LEVEL_BED",
			100 => "INSTALL_CARSEAT",
			101 => "NIGHT_VISION",
			102 => "COLOR",
			103 => "WIDTH_FRAME",
			104 => "WARDROBE",
			105 => "FEATURES_WARDROBE",
			106 => "NECK",
			107 => "STORAGE_TRAY",
			108 => "TOY_BOX",
			109 => "BOXES",
			110 => "",
		),
		"OFFERS_LIMIT" => "0",
		"TEMPLATE_THEME" => "",
		"DISPLAY_NAME" => "Y",
		"DETAIL_PICTURE_MODE" => "IMG",
		"ADD_DETAIL_TO_SLIDER" => "N",
		"DISPLAY_PREVIEW_TEXT_MODE" => "H",
		"PRODUCT_SUBSCRIPTION" => "N",
		"SHOW_DISCOUNT_PERCENT" => "N",
		"SHOW_OLD_PRICE" => "N",
		"SHOW_MAX_QUANTITY" => "N",
		"DISPLAY_COMPARE" => "N",
		"MESS_BTN_BUY" => "Купить",
		"MESS_BTN_ADD_TO_BASKET" => "В корзину",
		"MESS_BTN_SUBSCRIBE" => "Подписаться",
		"MESS_NOT_AVAILABLE" => "Нет в наличии",
		"USE_VOTE_RATING" => "N",
		"USE_COMMENTS" => "N",
		"BRAND_USE" => "N",
		"SECTION_URL" => "",
		"DETAIL_URL" => "",
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_GROUPS" => "Y",
		"SET_TITLE" => "Y",
		"SET_BROWSER_TITLE" => "Y",
		"BROWSER_TITLE" => "-",
		"SET_META_KEYWORDS" => "Y",
		"META_KEYWORDS" => "-",
		"SET_META_DESCRIPTION" => "Y",
		"META_DESCRIPTION" => "-",
		"SET_STATUS_404" => "Y",
		"ADD_SECTIONS_CHAIN" => "Y",
		"ADD_ELEMENT_CHAIN" => "Y",
		"USE_ELEMENT_COUNTER" => "Y",
		"PRICE_CODE" => array(
			0 => "BASE",
			1 => "MARGIN",
		),
		"USE_PRICE_COUNT" => "N",
		"SHOW_PRICE_COUNT" => "1",
		"PRICE_VAT_INCLUDE" => "Y",
		"PRICE_VAT_SHOW_VALUE" => "N",
		"CONVERT_CURRENCY" => "N",
		"BASKET_URL" => "/personal/basket.php",
		"ACTION_VARIABLE" => "action",
		"PRODUCT_ID_VARIABLE" => "id",
		"USE_PRODUCT_QUANTITY" => "N",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PARTIAL_PRODUCT_PROPERTIES" => "Y",
		"PRODUCT_PROPERTIES" => array(
		),
		"LINK_IBLOCK_TYPE" => "",
		"LINK_IBLOCK_ID" => "",
		"LINK_PROPERTY_SID" => "",
		"LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
		"OFFERS_FIELD_CODE" => array(
			0 => "ID",
			1 => "CODE",
			2 => "XML_ID",
			3 => "NAME",
			4 => "SORT",
			5 => "PREVIEW_TEXT",
			6 => "PREVIEW_PICTURE",
			7 => "",
		),
		"OFFERS_PROPERTY_CODE" => array(
			0 => "SIZE",
			1 => "COLOR",
			2 => "",
		),
		"OFFERS_SORT_FIELD" => "sort",
		"OFFERS_SORT_ORDER" => "asc",
		"OFFERS_SORT_FIELD2" => "id",
		"OFFERS_SORT_ORDER2" => "asc",
		"OFFERS_CART_PROPERTIES" => array(
			0 => "SIZE",
			1 => "COLOR",
		),
		"ADD_PICT_PROP" => "-",
		"LABEL_PROP" => "-",
		"OFFER_ADD_PICT_PROP" => "-",
		"OFFER_TREE_PROPS" => array(
			0 => "-",
		),
		"MESS_BTN_COMPARE" => "Сравнение",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"CHECK_SECTION_ID_VARIABLE" => "N",
		"PAGE_REVIEWS_COUNT" => "10"
	),
	false
);?>

<script type="text/javascript">
$(function() {
	//
		var _GET = window.location.search.substring(1).split("&");
		if (_GET) {
			for (var i=0; i<_GET.length; i++) {
				var getVar = _GET[i].split("=");
				if (getVar[0] == "PAGEN_1") {
					setTimeout(function() {
						$('a.item-tabs__link[href=#reviews]').click();
					}, 10);
					$('html, body').scrollTop($('.item-tabs').offset().top);
					//$('#moreLinkReview').click();
					break;
				}
			}
		}
		//
});
</script>

<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>